# Generated by Django 2.1.1 on 2018-11-20 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='name',
            field=models.CharField(default='Unknown', error_messages={'unique': 'The room name is already taken!'}, max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='persist_messages',
            field=models.BooleanField(default=False),
        ),
    ]
