# Generated by Django 2.1.1 on 2018-11-27 23:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_auto_20181126_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='name',
            field=models.CharField(default='Unknown', error_messages={'unique': 'The room name is already taken!'}, max_length=15, unique=True, validators=[django.core.validators.RegexValidator(code='invalid-name', inverse_match=True, message='The given room name is invalid! Beware of using underscores in the beginning.', regex='^__\\c*')]),
        ),
    ]
