# Generated by Django 2.1.1 on 2018-11-12 06:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('game', '0002_save_player'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_name', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('player', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='game_client', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
