# Generated by Django 2.1.1 on 2018-11-20 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_client'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='channel_name',
            new_name='channel_game',
        ),
        migrations.AddField(
            model_name='client',
            name='channel_chat',
            field=models.TextField(blank=True, null=True),
        ),
    ]
